-- Initial Schema Setup
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE public.ai_memories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  vector vector(1536) NOT NULL,
  metadata jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  username text,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX ai_memories_vector_idx 
ON public.ai_memories 
USING ivfflat (vector vector_cosine_ops)
WITH (lists = 100);

CREATE INDEX profiles_username_idx ON public.profiles (username);

ALTER TABLE public.ai_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User access to own memories" ON public.ai_memories
FOR ALL USING (
  (metadata->>'userId')::uuid = auth.uid()
);

CREATE POLICY "Public read access to session memories" ON public.ai_memories
FOR SELECT USING (
  metadata->>'sessionId' IS NOT NULL
);

CREATE POLICY "User can view own profile" ON public.profiles
FOR SELECT USING (id = auth.uid());

CREATE POLICY "User can update own profile" ON public.profiles
FOR UPDATE USING (id = auth.uid());
