BEGIN;

-- Create extensions
CREATE EXTENSION vector;

-- Create tables
CREATE TABLE public.ai_memories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  vector vector(1536) NOT NULL,  -- Match embedding dimensions
  metadata jsonb NOT NULL
);

-- Create profiles table
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id),
  username text,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS ai_memories_vector_idx 
ON public.ai_memories 
USING ivfflat (vector vector_cosine_ops)
WITH (lists = 100);

CREATE INDEX profiles_username_idx ON public.profiles (username);

-- Add these after table creation
-- Enable RLS
ALTER TABLE public.ai_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- AI Memories Policies
CREATE POLICY "User access to own memories" ON public.ai_memories
FOR ALL USING (
  (metadata->>'userId')::uuid = auth.uid()
);

CREATE POLICY "Public read access to session memories" ON public.ai_memories
FOR SELECT USING (
  metadata->>'sessionId' IS NOT NULL
);

-- Profiles Policies
CREATE POLICY "User can view own profile" ON public.profiles
FOR SELECT USING (id = auth.uid());

CREATE POLICY "User can update own profile" ON public.profiles
FOR UPDATE USING (id = auth.uid());

-- ... rest of your security policies and functions from supabase-setup.sql ...

COMMIT; 